spring.cloud:
  function:
    definition: paymentProcessor
  stream:
    bindings:
      paymentProcessor-in-0:
        destination: order-event
      paymentProcessor-out-0:
        destination: payment-event
    kafka:
      streams:
        binder:
          replication-factor: 1
